[package]
name = "wiki-langs"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*"
csv = "*"
html5ever = "*"
reqwest = "*"
scraper = "*"
select = "*"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
url = "*"
uuid = { version = "*", features = ["v4"] }
