[package]
name = "wiki-langs"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "*"
html5ever = "*"
reqwest = "*"
scraper = "*"
select = "*"
serde = "*"
tokio = { version = "1", features = ["full"] }
uuid = { version = "*", features = ["v4"] }
url = "*"
