on:
  schedule:
    - cron: "0 */2 * * *"

name: run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - name: run
        uses: actions-rs/cargo@v1
        with:
          command: run
      - name: commit csv tables
        uses: EndBug/add-and-commit@v9
        with:
          author_name: micah teeuws
          author_email: tutmirage@gmail.com
          message: 'update csv tables'
          add: '*.csv'
      - name: commit readme
        uses: EndBug/add-and-commit@v9
        with:
          author_name: micah teeuws
          author_email: tutmirage@gmail.com
          message: 'update readme'
          add: '*.md'

